insert into Sql1259724_5.autori (id_autore, nome, cognome)
values  (1, 'Vale', 'Vale'),
        (2, 'J.K ', 'Rowling'),
        (3, 'Italo', 'Calvino'),
        (42, 'Robert L.', 'Stevenson'),
        (43, 'STENDHAL', 'LA NEWTON'),
        (34, 'Luigi', 'Santucci'),
        (35, 'IGNAZIO', 'SEMILIA'),
        (36, 'Cesare ', 'Pavese'),
        (37, 'Albert', 'Camus'),
        (38, 'Agostino', 'Villa'),
        (4, 'Alessandro ', 'Manzoni'),
        (5, 'Riccardo', 'Bacchelli'),
        (6, 'Joseph', 'Conrad'),
        (41, 'VASCO ', 'PRATOLINI'),
        (7, 'Fernanda', 'Pivano'),
        (40, 'Lev ', 'Tolstoj'),
        (33, 'Fernando ', 'Pessoa'),
        (39, 'Gianna', 'Schelotto'),
        (8, 'Stephen', 'King'),
        (9, 'Poul', 'Anderson'),
        (10, 'C.S.', 'Lewis'),
        (11, 'Giuseppe', 'Marotta'),
        (12, 'Dino', 'Buzzati'),
        (13, 'Pieter', 'Aspe'),
        (14, 'Charlotte', 'Brontë'),
        (44, 'Cesare', 'Segre');